actions:
  - action: package.install
    list:
      - bash
      - bat
      - curl
      - dive
      - ffmpeg
      - git
      - imagemagick
      - jq
      - keepassxc
      - mailhog
      - mysql
      - php
      - redis
      - wget
  - action: command.run
    name: curl -o composer-installer https://getcomposer.org/installer && bash composer-installer --install-dir=/usr/local/bin --filename=composer
  - action: file.copy
    from: .bashrc
    to: ~/.bashrc
    template: false
  - action: file.copy
    from: .bash_profile
    to: ~/.bash_profile
    template: false
  - action: file.copy
    from: .git-completion.bash
    to: ~/.git-completion.bash
    template: false
  - action: file.copy
    from: .vimrc
    to: ~/.vimrc
    template: false
